language: python
sudo: false
python:
  - 3.4
env:
  global:
    - HOME=/home/travis
    - WORKON_HOME=$HOME/.pew
  matrix:
    - TOXENV="py34" PYTHON=3.4.6
    - TOXENV="py35" PYTHON=3.5.3
    - TOXENV="py36" PYTHON=3.6.0

install:
  - pip install pew
  - mkdir $WORKON_HOME
  - pew install $PYTHON
  - pew new -d venv --python=$(pew locate_python $PYTHON) -i tox -i mypy-lang
script: pew in venv tox -e $TOXENV
