language: python
sudo: false
python:
  - 3.4
env:
  global:
    - HOME=/home/travis
    - WORKON_HOME=$HOME/.pew
  matrix:
    - TOXENV="py35" PYTHON=3.5.3

install:
  - pip install pew
  - mkdir $WORKON_HOME
  - pew install $PYTHON
  - pew new -d py35 --python=$(pew locate_python $PYTHON) -i tox -i mypy-lang
script: pew in py35 tox -e $TOXENV
